In [16]:
import pandas as pd
import numpy as np
import h5py
import tables
from scipy.spatial import distance
from numpy.linalg import norm
import random
import spacy
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
conda install -c conda-forge spacy

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/arabi/anaconda3/envs/env

  added / updated specs:
    - spacy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.12.7  |       ha878542_0         143 KB  conda-forge
    catalogue-2.0.8            |   py39hf3d152e_1          32 KB  conda-forge
    certifi-2022.12.7          |     pyhd8ed1ab_0         147 KB  conda-forge
    commonmark-0.9.1           |             py_0          46 KB  conda-forge
    confection-0.0.4           |   py39hcca971b_1          61 KB  conda-forge
    cymem-2.0.7                |   py39h5a03fae_1          42 KB  conda-forge
    cython-blis-0.7.9          |   py39h2ae25f5_1         9.0 M

In [3]:
conda install -c anaconda pytables

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda


Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/arabi/anaconda3/envs/env

  added / updated specs:
    - pytables


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blosc-1.20.1               |       hd408876_0          81 KB  anaconda
    bzip2-1.0.8                |       h7b6447c_0         105 KB  anaconda
    ca-certificates-2023.01.10 |       h06a4308_0         127 KB  anaconda
    certi

In [20]:
h5file = tables.open_file("document_scores.h5", driver="H5FD_CORE")

In [24]:
#a = h5file.create_array(h5file.root, "array")
h5file.close()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [7]:
data = pd.DataFrame()
data['name'] = ['shusmi','mou',"sadid"]
data['class'] = ['seven','eight',"nine"]
data.to_hdf("dummy.h5",key='data',mode='w',index = False)

In [6]:
df = pd.read_hdf("dummy.h5")
print(df['name'])
a = df[df['name'] == 'mou']
print(a)

0    shusmi
1       mou
2     sadid
Name: name, dtype: object
  name  class
1  mou  eight


In [4]:

'''f = h5py.File('document_scores.h5', 'r')
data = f
f.close()'''
#print(data[10])

data = pd.read_hdf("dummy.h5")

In [5]:
print(data.head(5))

AttributeError: 'File' object has no attribute 'head'

In [9]:
d1 = np.random.random(size = (1000,20))
d2 = np.random.random(size = (1000,200))
hf = h5py.File('data.h5', 'w')
hf.create_dataset('dataset_1', data=d1)
hf.create_dataset('dataset_2', data=d2)
hf.close()

In [12]:
hf = h5py.File('data.h5', 'r')
n1 = hf.get('dataset_1')
n1

<HDF5 dataset "dataset_1": shape (1000, 20), type "<f8">

In [2]:
hf = h5py.File('document_scores.h5', 'r')
hf.keys()

<KeysViewHDF5 ['unique_IDF']>

In [3]:
n1 = hf.get('unique_IDF')
n1 = np.array(n1)
n1

array(['pmid_title_abstract_0.csv', 'pmid_title_abstract_1.csv',
       'pmid_title_abstract_10.csv', 'pmid_title_abstract_100.csv',
       'pmid_title_abstract_101.csv', 'pmid_title_abstract_102.csv',
       'pmid_title_abstract_103.csv', 'pmid_title_abstract_104.csv',
       'pmid_title_abstract_105.csv', 'pmid_title_abstract_106.csv',
       'pmid_title_abstract_107.csv', 'pmid_title_abstract_108.csv',
       'pmid_title_abstract_109.csv', 'pmid_title_abstract_11.csv',
       'pmid_title_abstract_110.csv', 'pmid_title_abstract_111.csv',
       'pmid_title_abstract_112.csv', 'pmid_title_abstract_113.csv',
       'pmid_title_abstract_114.csv', 'pmid_title_abstract_115.csv',
       'pmid_title_abstract_116.csv', 'pmid_title_abstract_117.csv',
       'pmid_title_abstract_118.csv', 'pmid_title_abstract_119.csv',
       'pmid_title_abstract_12.csv', 'pmid_title_abstract_120.csv',
       'pmid_title_abstract_121.csv', 'pmid_title_abstract_122.csv',
       'pmid_title_abstract_123.csv', 'pm

In [5]:
x1 = hf['unique_IDF']
x1.keys()
x2 = x1['pmid_title_abstract_1.csv']

In [6]:
print(x2.keys())

xx = x2['_ref']
xx = np.array(xx)
print(xx)

x3 = x2['V']
x3 = np.array(x3)
val = x3
x3.shape

<KeysViewHDF5 ['V', '_ref']>
[ 98314  98315  98316 ... 198053 198054 198055]


(99742, 200)

In [2]:
hf.close()

NameError: name 'hf' is not defined

In [45]:
val

array([[-0.05965453, -0.00578227, -0.01279581, ..., -0.07290949,
        -0.06872617,  0.05075565],
       [-0.13727423,  0.03843192,  0.06886609, ..., -0.02066254,
        -0.06638643,  0.00965991],
       [ 0.04905552, -0.00602249, -0.09208383, ...,  0.04191353,
        -0.01943428, -0.08658876],
       ...,
       [ 0.05697763,  0.05986729,  0.01519381, ...,  0.00809084,
         0.14198401,  0.06788855],
       [ 0.11953789,  0.1710377 ,  0.00536755, ..., -0.02107219,
        -0.08555055, -0.01661236],
       [ 0.00332061,  0.14810488, -0.08909484, ...,  0.04461067,
         0.15837549,  0.02542045]])

In [2]:
hf = h5py.File('document_scores.h5', 'r')
#hf.keys()
x1 = hf['unique_IDF']
x1.keys()
ddf = pd.DataFrame()
cnt = 0
for key, val in x1.items():
        df = pd.DataFrame()
        #print("    %s: %s" % (key, val))
        x2 = x1[key]['_ref']
        x2 = np.array(x2)
        print(x2)
        print(str(key))
        x3 = x1[key]['V']
        print(np.array(x3))
        
        df['pmid'] = x2
        df['file'] = str(key)
        #ddf = ddf.append(df, ignore_index = True)
        ddf = pd.concat([ddf, df], axis=0, ignore_index=True)
        cnt += 1
        if cnt == 2:
            break
#x1 = np.array(x1)

#x2 = x1[0]
#x2.keys()


[    0     1     2 ... 98311 98312 98313]
pmid_title_abstract_0.csv
[[ 0.12220564 -0.06521089 -0.04725014 ...  0.00526334 -0.05353307
  -0.03251462]
 [-0.0509406  -0.10806097  0.02433374 ... -0.09332399  0.0228999
  -0.01231188]
 [-0.03098825  0.0273562  -0.06008766 ... -0.08318502 -0.04810697
   0.09462893]
 ...
 [-0.04976247  0.01020731 -0.10382641 ...  0.02599197  0.06204781
   0.04910607]
 [-0.1489028  -0.04110633 -0.19022238 ... -0.06564088  0.02153881
  -0.03135086]
 [-0.00162936  0.02143402 -0.02685589 ...  0.00458998  0.14804929
  -0.04502128]]
[ 98314  98315  98316 ... 198053 198054 198055]
pmid_title_abstract_1.csv
[[-0.05965453 -0.00578227 -0.01279581 ... -0.07290949 -0.06872617
   0.05075565]
 [-0.13727423  0.03843192  0.06886609 ... -0.02066254 -0.06638643
   0.00965991]
 [ 0.04905552 -0.00602249 -0.09208383 ...  0.04191353 -0.01943428
  -0.08658876]
 ...
 [ 0.05697763  0.05986729  0.01519381 ...  0.00809084  0.14198401
   0.06788855]
 [ 0.11953789  0.1710377   0.00536755 

In [3]:
ddf.head(5)

pmid                       file
0     0  pmid_title_abstract_0.csv
1     1  pmid_title_abstract_0.csv
2     2  pmid_title_abstract_0.csv
3     3  pmid_title_abstract_0.csv
4     4  pmid_title_abstract_0.csv

In [4]:
abc = ddf.to_numpy()
abc[0][0]
bbc = x1[abc[abc.shape[0]-1][1]]
#bbc = x1[abc[0][1]]
bbc

<HDF5 group "/unique_IDF/pmid_title_abstract_1.csv" (2 members)>

In [5]:
d = bbc['V']
d = np.array(d)


In [6]:
for key, val in bbc.attrs.items():
        #print("    %s: %s" % (key, val))
        #print(" %s" % (val[0]))
        print(" %s" % (val))
        print(key)
        

In [7]:
ff = bbc['_ref']
ff = np.array(ff)
a = np.where(ff==0)[0][0]
bbc['_ref'][a]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [21]:
arr2 = bbc['V'][1]
arr2

array([-0.13727423,  0.03843192,  0.06886609, -0.07069801, -0.03271987,
        0.15505287,  0.04059191, -0.02411703, -0.12887137,  0.0823396 ,
        0.08546727, -0.00042393,  0.01509653, -0.07819805, -0.06666958,
        0.09474602,  0.05212683,  0.00119547,  0.06910057,  0.05714077,
       -0.00033923,  0.00837511,  0.05378158,  0.0461118 , -0.03504255,
       -0.07884597, -0.05030205,  0.0164373 ,  0.0187426 ,  0.08425867,
       -0.03856608, -0.14377997, -0.01036226, -0.00171846,  0.12107549,
       -0.02554212, -0.06585785,  0.03999596,  0.12881359, -0.05469795,
       -0.06904515,  0.08710575,  0.00098677, -0.06341201,  0.01621584,
        0.12555587,  0.10257498, -0.0812101 , -0.05058759,  0.0183581 ,
       -0.11239972,  0.12076802,  0.05203338,  0.03357297, -0.11926784,
        0.10493612, -0.1174612 , -0.06173019,  0.0324309 , -0.0642478 ,
        0.06796959, -0.06123084,  0.06446921,  0.08236705, -0.14080476,
       -0.03755753,  0.0361677 , -0.05091824,  0.02425793, -0.02

In [22]:
arr1 = bbc['V'][2]
arr1

array([ 0.04905552, -0.00602249, -0.09208383,  0.0464174 , -0.01324679,
       -0.02215121,  0.05441623,  0.02131699, -0.04554901,  0.11186645,
        0.06708385, -0.01914388,  0.14665751,  0.04047838,  0.02262859,
        0.02187702,  0.07254481,  0.04535825,  0.06860216,  0.0679987 ,
        0.07701944,  0.059563  ,  0.01529675, -0.01808798,  0.02720829,
       -0.0635517 , -0.03934824, -0.0975143 ,  0.02611034, -0.15208467,
        0.11464362, -0.00896658,  0.061862  ,  0.10411696, -0.02650534,
        0.0640656 ,  0.00339769, -0.04245843, -0.07030892,  0.01098805,
        0.09374675, -0.04165111, -0.03746168, -0.17417612, -0.03238775,
       -0.06296456,  0.00081511,  0.09240469, -0.00124061, -0.103001  ,
       -0.05842783,  0.1306029 , -0.06869222,  0.03416561,  0.02635573,
       -0.12083514, -0.01915427, -0.05761654, -0.03695603,  0.04703898,
       -0.01208242,  0.0792902 ,  0.04242413, -0.01907945,  0.08132202,
       -0.03429523,  0.07934352, -0.15015951, -0.07655725, -0.02

In [23]:


def cosine_similarity_calc(vec_1,vec_2):
    
    sim = np.dot(vec_1,vec_2)/(np.linalg.norm(vec_1)*np.linalg.norm(vec_2))
    
    return sim
def cosine_similarity2(a, b):
    nominator = np.dot(a, b)
    
    a_norm = np.sqrt(np.sum(a**2))
    b_norm = np.sqrt(np.sum(b**2))
    
    denominator = a_norm * b_norm
    
    cosine_similarity = nominator / denominator
    
    return cosine_similarity
print(1.0-distance.cosine(arr1, arr2))
cosine = np.dot(arr1,arr2)/(norm(arr1)*norm(arr2))
print(cosine)
csine = cosine_similarity2(arr1, arr2)
print(csine)
cs1 = cosine_similarity_calc(arr1, arr2)
print(cs1)

a1 = arr1.reshape(1, -1)
a2 = arr2.reshape(1, -1)
cs2 = cosine_similarity(a1, a2)
print(cs2[0][0])

-2.8190319922849483e-07
-2.8190319921114765e-07
-2.8190319921114765e-07
-2.8190319921114765e-07
-2.819031992111476e-07


In [110]:
ddf[ddf['pmid'] == 198055]

pmid                       file
198055  198055  pmid_title_abstract_1.csv

In [ ]:
data = pd.DataFrame()
data['id'] = ['a','b','c']
data['val'] = [1,22,3]
data = data.set_index('id').to_dict()['val']
if 'a' in data:
    print(data.get('a'))
else:
    print("no")

In [23]:
random.randint(2000, 2020)

2005